import Head from 'next/head'
import AppNavBar from '../components/AppNavBar';
import AppCardBullets from '../components/AppCardBullets';


export default function Home() {


  let x = "Meu Webapp";

  const bullets_today = [
    {type: 'event', title: ' Atividade sobre componente React'},
    {type: 'task', title: ' Palavras Chaves - bullet journal, github issues'},
  ];

  const bullets_tomorrow = [
    {type: 'event', title: 'Aprendendo sobre bullets'},
    {type: 'task', title: 'Consegui'}
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       
        <AppNavBar title={x}/>
        <AppCardBullets date="18/09/2021" bullets={bullets_today}/>
        <AppCardBullets date="19/09/2021" bullets={bullets_tomorrow}/>
      </main>
    </div>
  )
}